### ISSUE TITLE
SD card creation script removed

### ISSUE THREAD

**Issue by worleydl** [MiSTer-devel/Linux_Image_creator_MiSTer#1]
Any reason the create_sd.sh script was removed? It's handy for getting the SD card prepped in Linux.

This documentation still references it: https://github.com/MiSTer-devel/Main_MiSTer/wiki/Bootable-SD-card.  I worked around it by copying it from an older revision and having it point at the new create_img script instead of copy_to_sd.

I can open a PR if you want, but figured I'd check to see if there was something I was missing.

**Comment by sorgelig** [comment]
SD making card has been replaced by script making the Image after layout change. Since most users are Windows users, it's supposed to use SD installer tool.
There you can find a modified script for new card layout: http://www.atari-forum.com/viewtopic.php?p=340314#p340314

**Comment by sorgelig** [comment]
Btw, how you came to Bootable-SD-card page? I've thought i've removed all links to this outdated guide.

**Comment by worleydl** [comment]
I had it bookmarked.  I'll skip the PR since this was intentional. Thanks!

**Comment by sorgelig** [comment]
It's not really intentional. It's dropped due to low priority and because i use windows utility myself. If there will be support from someone else, then it can be included, but script need to be moved to Linux releases, so it will use the same files as windows installer. Take a look in https://github.com/MiSTer-devel/SD-Installer-Win64_MiSTer
If you want, create script to install these files and i will include it in next release. You can use script from forum and tweak it if needed. 
I just don't want to be involved into developing and testing this scrip as i have many other tasks.
